#代理host
httpclient:
  config:
    # 代理的host
    proxyhost: localhost
    # 代理端口
    proxyPort: 1080
    # 重试次数
    retryTime: 3
    # 长连接时间 单位s
    keepAliveTime: 30
    # 连接池最大连接数
    connMaxTotal: 5
    maxPerRoute: 5
    # 连接超时时间，单位ms
    connectTimeout: 1000
    # 请求超时时间
    connectRequestTimeout: 2000
    # sock超时时间
    socketTimeout: 5000
    # 连接存活时间，单位s
    timeToLive: 60
spring:
  datasource:
    #url: jdbc:mysql://172.24.8.100:3306/varys?characterEncoding=utf-8
    url: jdbc:mysql://176.122.176.71:3306/varys?characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 12cf0d30
    #username: test
    #password: test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: club.projectgaia.varys.utils.MySQL5InnoDBDialectUtf8mb4
logging:
    level:
        club.projectgaia: info
    file: /home/magneto/log/varys.log
    root: INFO


