#代理host
httpclient:
  config:
    # 代理的host
    proxyhost: localhost
    # 代理端口
    proxyPort: 1080
    # 重试次数
    retryTime: 3
    # 长连接时间 单位s
    keepAliveTime: 30
    # 连接池最大连接数
    connMaxTotal: 5
    maxPerRoute: 5
    # 连接超时时间，单位ms
    connectTimeout: 1000
    # 请求超时时间
    connectRequestTimeout: 2000
    # sock超时时间
    socketTimeout: 50000
    # 连接存活时间，单位s
    timeToLive: 600
spring:
  datasource:
    url: jdbc:mysql://${HOST}:3306/varys?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
    #url: jdbc:mysql://176.122.176.71:3306/varys?characterEncoding=utf-8
    #type: com.alibaba.druid.pool.DruidDataSource
    username: ${MYSQL_USER}
    password: ${MYSQL_PWD}
    #username: test
    #password: test
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: club.projectgaia.varys.utils.MySQL5InnoDBDialectUtf8mb4
    show-sql: false
logging:
  file: ${LOG_PATH}
  root: INFO
#  level:
#    org.springframework.security:
#      - debug
#      - info
#    org.springframework.web: error
#    org.hibernate.SQL: debug
#    org.hibernate.engine.QueryParameters: debug
#    org.hibernate.engine.query.HQLQueryPlan: debug
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
lianjia:
  sitemap-path: /home/magneto/lianja

